### ISSUE TITLE
Правки 3.1

### ISSUE THREAD

**Issue by AndreyFedarovich** [digitalshop24/bon#34]
**1)** Надпись _**Комментарии к посту**_  ведет себя странно
![screen shot 2016-09-15 at 12 32 33 pm](https://cloud.githubusercontent.com/assets/15676325/18545178/a92fc522-7b40-11e6-969a-ff16e203ec35.png)
**2)** Нужно сделать функционал удаления (страница /invitations)
![screen shot 2016-09-15 at 6 18 19 pm](https://cloud.githubusercontent.com/assets/15676325/18555523/d83559d8-7b70-11e6-932c-ed95044b693f.png)

**Comment by reiro** [comment]
2 - готово
