### ISSUE TITLE
Правки new

### ISSUE THREAD

**Issue by yuliyakislach** [digitalshop24/bon#48]
Собаки в шапке
- [ ] **Дизайн: (1)**
  - [ ] Сделать изображения собак одинакового размера (1.1)
  - [ ] Растянуть по шапке с большим интервалом между друг другом (1.2)
  - [x] Под собаками надо сделать подписи = название раздела (1.3)
  - [x] Управление категориями и миниатюрами на бэкенде. (1.4)
  - [x] Возможность добавлять/удалять категории + их фото (1.5)
- [x] **Слайдер (2)**
  - [x] Убрать кнопку "Читать далее". (2.1)
  - [x] Не только заголовок должен вести на статью, но и текст. (2.2)
  - [x] Сделать отдельный функционал для слайдера.  (2.3)
    Возможность добавлять в главный слайдер не только статьи, но просто фото+заголовок+текст
- [x] **Создание поста (3)**
  - [x] Сделать поля с оценками необязательными. (3.1)
- [x] **О проекте (4)**
  - [x] Добавить возможность редактировать текст после авторизации (4.1)
    ![image](https://cloud.githubusercontent.com/assets/18350195/19511284/5d2c28cc-95ef-11e6-84f6-615ecd2199dd.png)
- [ ] **Подвал (5)**
  **Бэкенд:**
  - [ ] возможность убрать добавить соц. сети, (4.2)
  - [ ] возможность убрать добавить/удалить пункт меню (4.3)
    ![image](https://cloud.githubusercontent.com/assets/18350195/19511342/94f188c4-95ef-11e6-9e3b-37e141220bd9.png)
- [ ] **Категории - собака на красном фоне (6)**
  Я могу сама редактировать это? Фон, или заменить это на фото например, вместо собаки на фоне? 
  Есть ли ограничение внутри каждого раздела по кол-ву постов, которое отображается на странице?
  ![image](https://cloud.githubusercontent.com/assets/18350195/19760477/9e208f70-9c3a-11e6-9e51-5d750a51d2df.png)
- [x] **Можно ли добавить функционал корректировки фото, чтобы избегать ситуации как сейчас, когда карточка залетает на изображение. (7)**
  ![image](https://cloud.githubusercontent.com/assets/18350195/19511400/c7b76da0-95ef-11e6-9065-ff99b2b7b05c.png)

- [ ] Не забыть
  - [ ] Пагинация постов
  - [x] Пофиксить фоку в категории
  - [x] Кнопку для добавления постов/категорий продублировать сверху
  - [ ] Will_paginate

**Comment by kkan** [comment]
1.4, 1.5 - одно и то же? 
можно же:
![image](https://cloud.githubusercontent.com/assets/7046667/19755320/a0764ca0-9c1d-11e6-8c8d-9fbd1bb0962d.png)
или что имеется в виду?

@kkan а с интерфейса для клиентки? на фронте?

**Comment by kkan** [comment]
2.3 - в слайдер будут идти только объекты новой модели Slider или посты тоже?

@kkan и то, и другое

**Comment by kkan** [comment]
7 - можно, только не делал такого никогда еще

**Comment by kkan** [comment]
4.2 - это должны быть кнопки шаринга?

да, и они, кстати, не работают

**Comment by camorazrushimoe** [comment]
"Я могу сама редактировать это? Фон, или заменить это на фото например, вместо собаки на фоне?
Есть ли ограничение внутри каждого раздела по кол-ву постов, которое отображается на странице?"

@yuliyakislach а это к кому вопросы? это как я понимаю клиент что-то спрашивает. В чем смысл задавать эти вопросы Косте?

**Comment by kkan** [comment]
1.1 - хз как делать, проще картинки переделать

**Comment by kkan** [comment]
@camorazrushimoe @yuliyakislach по поводу 1.2 можно так сделать например:
![image](https://cloud.githubusercontent.com/assets/7046667/20034374/c413807c-a3cc-11e6-96e9-6247189db3be.png)
