### ISSUE TITLE
Правки по сайту

### ISSUE THREAD

**Issue by camorazrushimoe** [digitalshop24/bon#55]
- [x] 1. На главной странице слайдер:
![image](https://cloud.githubusercontent.com/assets/8914398/20028401/73a5e048-a341-11e6-851f-d1a94d7ed70c.png)

В макете:
![image](https://cloud.githubusercontent.com/assets/8914398/20028405/8953d4c2-a341-11e6-865e-c8c8041badd4.png)

Под фото из слайдера есть полоса которая визуально выделяет блок. Так же под слайдером нет точек, а кол-во слайдов показывается цифрами. Так же есть стрелки для перелистывания. 
  - [x] полоса
  - [x] убрать точки
  - [x] кол-во слайдов
  - [x] стрелки

- [x] 2. Перечень всех постов:
![image](https://cloud.githubusercontent.com/assets/8914398/20028438/64cd6360-a342-11e6-8a6a-0b8394138f89.png)

  - [x] В списке всех постов должно быть показано какие посты отображаются в слайдере на главной. 
  - [ ] Должна быть возможность менять порядок постов. Посты должны показываться в этом порядке. 

- [x] 3. Убрать кнопки
Вот эти кнопки в категориях надо убрать:
![image](https://cloud.githubusercontent.com/assets/8914398/20028448/cc4b2464-a342-11e6-9727-e2576c7c971e.png)

- [x] 4. Если у поста есть описание то кнопка "Редактировать" залазит на текст:
![image](https://cloud.githubusercontent.com/assets/8914398/20028500/9501b19c-a344-11e6-9c43-ef03ebdc80e9.png)

- [ ] 5. Что-то не так с хештегами постов:
![image](https://cloud.githubusercontent.com/assets/8914398/19933948/192a5c42-a126-11e6-969f-b810a33b3862.png)

  - [x] Должна быть возможность прицепить к посту хештег. Далее возможность кликнуть по этому хештегу и отсортировать все посты связанные с ним. 
  - [ ] При написании хештега, должны предлагаться уже использованные хештеги. 

- [x] 6. Моб.версия расстояние от поста в слайдере до превью постов:
![image](https://cloud.githubusercontent.com/assets/8914398/20028545/d6f40266-a345-11e6-9668-b16748c131f0.png)

Это расстояние для всех слайдов задается размером самого длинного описания:
![image](https://cloud.githubusercontent.com/assets/8914398/20028549/ed4acf2c-a345-11e6-8b6b-f591323e1dce.png)

Такого быть не должно и если описание у слайда короткое, то желательно, что бы небыло такого большого пустого места на телефоне. 

- [x] 7. Должна быть возможность изменить порядок постов для слайдера:
![image](https://cloud.githubusercontent.com/assets/8914398/20028568/5ee3f3ca-a346-11e6-9af3-bdd256cf1207.png)

- [x] 8. Складывается впечатление что картинку в слайдере на главной странице надо опустить по ниже. Буквально на 1-2 px
![image](https://cloud.githubusercontent.com/assets/8914398/20028582/9ed3a80e-a346-11e6-9417-b0740bbd0fd7.png)

Может и ошибаюсь

- [x] 9. Моб версия страницы поста. 

###**Выглядит так:**
![image](https://cloud.githubusercontent.com/assets/8914398/20028607/830f94a6-a347-11e6-9903-e6c83c7b4f4c.png)

###**Должна выглядеть так:**
![image](https://cloud.githubusercontent.com/assets/8914398/20028605/6eafd02a-a347-11e6-896a-16050bbbe037.png)

Белая штука на мою.версии должна залазить на картинку чуть-чуть.

- [x] 10. Страничка "Обо мне" нельзя изменить текст:
![image](https://cloud.githubusercontent.com/assets/8914398/20028622/14314362-a348-11e6-8c98-60b71eb90287.png)
 
Должна быть возможность изменить этот текст.

**Comment by kkan** [comment]
@camorazrushimoe что делать со стрелочками в слайдере на главной на мобильных устройствах?

**Comment by kkan** [comment]
@camorazrushimoe и еще походу надо "Показать еще" сделать на странице категории для постов
