### ISSUE TITLE
Правки по сайту

### ISSUE THREAD

**Issue by camorazrushimoe** [digitalshop24/bon#62]
Ряд доработок по сайту:
http://russel-jack.ru/

Бон начал наполнять сайт контентом и столкнулся с рядом проблем. Далее о проблемах которые надо помочь решить. 

**Важный момент.** Бон просто пес, и мог не заметить или не знать как объяснить каких-то простых вещей. По этому даже есть тут нет какой-то задачи, но ты видишь что это можно поправить/улучшить. Надо поправить/улучшить. 

Правочки от Бона:

- [x] 1) Нет возможности разместить пост не поставив оценку заведению. (на промежуточной версии была опция разместить без оценки как сам пост, так и секции)

- [x] 2) Бон - "Слайдер на главной - можно убрать белую плашку с текстами?"

Этот белый блок, на фотке, надо убрать:
![image](https://cloud.githubusercontent.com/assets/8914398/22459020/fdf40272-e7af-11e6-9b04-42ab12d9ba76.png)

Так же надо добавить галочку "Показывать анонс". По умолчанию галочка не активна и анонс не показывается. Если ее активировать на фотке появляется блок с анонсом. 

- [x] 3) Заголовки для страниц. 

Надо добавить возможность писать title и description для всех страниц. Для этого, когда авторизованы под админом. В этой менюшке:
![image](https://cloud.githubusercontent.com/assets/8914398/22459576/43f2a128-e7b2-11e6-8b98-efee4ac03a0f.png)

Должна появиться вкладка "SEO" (как-то отделена от других пунктов меню) жмем на нее и появляется попап где можно написать title и description. Так же должен быть текст "Рекомендуемая длинна 80 - 120 символов для titile и 140 - 180 для decsription".  

то что там напишем будет попадать в метатеги страницы на которой это написали.

- [x] 4) Что-то неладное произошло с собаками в шапке:
![image](https://cloud.githubusercontent.com/assets/8914398/22459899/82d767ce-e7b3-11e6-9159-e95aeaabcf4a.png)

Они и были немного разного размера, так дожно быть. Потому что одна собака сидит, вторая стоит и т.д. Но сейчас они прям вообще разного-разного размера. Это надо пофиксить.

- [x] 5) Соц.сеточки

В верху поста:
![image](https://cloud.githubusercontent.com/assets/8914398/22460786/9488151e-e7b7-11e6-8db3-478d3bddf6e0.png)

и в подвале страницы:
![image](https://cloud.githubusercontent.com/assets/8914398/22460792/9e8e83d6-e7b7-11e6-928f-02209a6c714d.png)

Репост в соц. сеточку идет через какой-то левый сайт/плагин. Надо сделать что бы репост был на прямую в соц.сеть. Без переадресация на третью сторону.

**Comment by kkan** [comment]
1. Бон - "Слайдер на главной - можно убрать белую плашку с текстами?" - можно не показывать ее, когда нет описания, например? что с каунтером слайдов?
![image](https://cloud.githubusercontent.com/assets/7046667/22562657/804a463e-e98e-11e6-9225-8f0837dbc339.png)
2. Что они никак с собаками не успокоятся? Хотя там и Влад конечно намутил.
Ну вот так будет:
![image](https://cloud.githubusercontent.com/assets/7046667/22562700/b58e7770-e98e-11e6-8501-ca0e40261caa.png)

**Comment by kkan** [comment]
https://bon-staging.herokuapp.com/

1. хм, посты можно было добавить. секции да, исправил
2. Плашка не отображается, если нету описания:
![image](https://cloud.githubusercontent.com/assets/7046667/22578759/31f087de-e9dc-11e6-9788-2bbe1b3ef172.png)
3. Задано значение по умолчанию.
![image](https://cloud.githubusercontent.com/assets/7046667/22578773/48646666-e9dc-11e6-8850-210ccdf12e24.png)
4. 
![image](https://cloud.githubusercontent.com/assets/7046667/22578792/6c11e872-e9dc-11e6-935a-8cbfae950d2c.png)
5. Теперь шаринг прямой. Метатеги для соцсетей теперь берутся из title и description. Также добавил метатеги для твиттера.

**Comment by camorazrushimoe** [comment]
@kkan можешь плиз мне доступы админа подсказать? не знаю как зайти в админку. там может юзера нового сделать, походу пароль старый поменяли
